SYNTHEA_FILE_MODELS = {
    "allergies.csv": AllergyRow,
    "careplans.csv": CarePlanRow,
    "claims_transactions.csv": ClaimTransactionRow,
    "claims.csv": ClaimRow,
    "conditions.csv": ConditionRow,
    "devices.csv": DeviceRow,
    "encounters.csv": EncounterRow,
    "imaging_studies.csv": ImagingStudyRow,
    "immunizations.csv": ImmunizationRow,
    "medications.csv": MedicationRow,
    "observations.csv": ObservationRow,
    "organizations.csv": OrganizationRow,
    "patients.csv": PatientRow,
    "payer_transitions.csv": PayerTransitionRow,
    "payers.csv": PayerRow,
    "procedures.csv": ProcedureRow,
    "providers.csv": ProviderRow,
    "supplies.csv": SupplyRow,
}